import { test, expect } from '@playwright/test';
// Labeled fixture output; no route/socket mocks. Built React -> real FastAPI.
test('five tabs render backend data, provider channels, and historical context', async ({ page, request }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const calls = (await (await request.get('/api/model-calls')).json()).calls;
  await page.goto('/');
  await expect(page.locator('.connection-state')).toContainText('实时连接');
  await page.getByRole('button', { name: '切换任务详情面板' }).click();
  const drawer = page.getByRole('region', { name: '任务详情' });
  await expect(drawer.getByTestId('drawer-context')).toContainText('FIXTURE-drawer-integration');
  await drawer.locator('.timeline-item summary').first().click();
  await expect(drawer).toContainText('FIXTURE assignment detail');
  await drawer.getByRole('tab', { name: '区域', exact: true }).click();
  await expect(drawer).toContainText('FIXTURE-region');
  await drawer.getByRole('tab', { name: '模型日志' }).click();
  await expect(drawer).toContainText(calls[0].decision_summary);
  await expect(drawer).toContainText('FIXTURE external provider output');
  await expect(drawer).toContainText('choices[0].message.reasoning_content');
  await expect(drawer).toContainText('Public provider reasoning summary');
  await expect(drawer).toContainText('not provided');
  await drawer.getByRole('tab', { name: '参数', exact: true }).click();
  await expect(drawer).toContainText('sea_area_km');
  await drawer.getByRole('tab', { name: 'AIS', exact: true }).click();
  await expect(drawer.locator('tbody tr').first()).toBeVisible();
  await page.getByRole('button', { name: '回放', exact: true }).click();
  await page.getByLabel('选择回放文件').selectOption('FIXTURE-details.jsonl');
  await expect(drawer.getByTestId('drawer-context')).toContainText('Historical replay');
  await drawer.getByRole('tab', { name: '时间线', exact: true }).click();
  await expect(drawer).not.toContainText('FIXTURE future event');
  await drawer.getByRole('tab', { name: '模型日志' }).click();
  await expect(drawer).toContainText('FIXTURE external provider output');
  await page.getByLabel('选择回放文件').selectOption('FIXTURE-legacy.jsonl');
  await drawer.getByRole('tab', { name: '参数', exact: true }).click();
  await expect(drawer).toContainText('Historical parameters: not provided');
  await drawer.getByRole('tab', { name: '模型日志' }).click();
  await expect(drawer).not.toContainText('FIXTURE external provider output');
  expect(errors).toEqual([]);
});
